apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: &cluster_name zalandodemo01 
  labels:
    application: spilo
    spilo-cluster: *cluster_name
spec:
  replicas: 3
  serviceName: *cluster_name
  template:
    metadata:
      labels:
        application: spilo
        spilo-cluster: *cluster_name
      annotations:
        iam.amazonaws.com/role: app-spilo
        scheduler.alpha.kubernetes.io/affinity: >
            {
                "podAntiAffinity": {
                  "requiredDuringSchedulingIgnoredDuringExecution": [
                    {
                        "labelSelector": {
                          "matchExpressions": [
                            {
                              "key": "spilo-cluster",
                              "operator": "In",
                              "values": ["zalandodemo01"]
                            }
                          ]
                         },
                         "topologyKey": "kubernetes.io/hostname" 
                    }
                  ]
                 }
            }
    spec:
      serviceAccountName: operator
      containers:
      - name: *cluster_name
        image: registry.opensource.zalan.do/acid/spilo-9.6:1.2-p17  # put the spilo image here
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8008
          protocol: TCP
        - containerPort: 5432
          protocol: TCP
        volumeMounts:
        - mountPath: /home/postgres/pgdata
          name: pgdata
        env:
        - name: ETCD_HOST
          value: 'test-etcd.default.svc.cluster.local:2379' # where is your etcd?
        - name: WAL_S3_BUCKET
          value: zalando-db-eu-central-1-spilo-dbaas
        - name: BACKUP_SCHEDULE
          value: "00 01 * * *"
        - name: LDAP_URL
          value: ldaps://corp-ldap.auth.zalando.com:636/ou=people,dc=zalan,dc=do
        - name: PATRONI_CONFIGURATION
          value: | ## https://github.com/zalando/patroni#yaml-configuration
            bootstrap:
              pg_hba:
                - hostnossl all all all reject
                - hostssl   all +zalandos all ldap ldapserver="localhost" ldapprefix="uid=" ldapsuffix=",ou=people,dc=zalan,dc=do"
                - hostssl   all all all md5
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: PGPASSWORD_SUPERUSER
          valueFrom:
            secretKeyRef:
              name: *cluster_name
              key: superuser-password
        - name: PGPASSWORD_ADMIN
          valueFrom:
            secretKeyRef:
              name: *cluster_name
              key: admin-password
        - name: PGPASSWORD_STANDBY
          valueFrom:
            secretKeyRef:
              name: *cluster_name
              key: replication-password
        - name: SCOPE
          value: *cluster_name
        - name: PGROOT
          value: /home/postgres/pgdata/pgroot
  volumeClaimTemplates:
  - metadata:
      labels:
        application: spilo
        spilo-cluster: *cluster_name
      annotations:
        volume.beta.kubernetes.io/storage-class: standard
      name: pgdata
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi

---
apiVersion: v1
kind: Endpoints
metadata:
  name: &cluster_name zalandodemo01
  labels:
    application: *cluster_name
subsets: []

---
apiVersion: v1
kind: Service
metadata:
  name: &cluster_name zalandodemo01
  labels:
    application: spilo
    spilo-cluster: *cluster_name
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432

---
apiVersion: v1
kind: Secret
metadata:
  name: &cluster_name zalandodemo01
  labels:
    application: spilo
    spilo-cluster: *cluster_name
type: Opaque
data:
  superuser-password: emFsYW5kbw==
  replication-password: cmVwLXBhc3M=
  admin-password: YWRtaW4=
